# Generated by Django 5.1.1 on 2024-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork',
            field=models.ImageField(upload_to='artmedia/'),
        ),
    ]
