# Generated by Django 5.1.1 on 2024-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_artwork_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='name',
            field=models.CharField(default='Ana', max_length=100),
        ),
    ]
