# Generated by Django 5.1.1 on 2024-12-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_artwork_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='name',
            new_name='artName',
        ),
    ]
