# Generated by Django 5.1.1 on 2024-12-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artwork_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homepage.artwork'),
        ),
    ]
